In [169]:
import numpy as np
import pandas as pd

In [170]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [171]:
df=pd.read_csv('gurgaon_properties.csv')

In [172]:
df.head()

,property_name,property_type,society,price_in_crore,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 56 Gurgaon,flat,smriti apartment,0.45,7500.0,600.0,Super Built up area 600(55.74 sq.m.),1,1,2,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",3.0,NaN,10+ Year Old,"['Sector 54 chowk metro station', 'Sector metr...",Gated society.\n4th floor.\nJust 400 meters fr...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
1,2 BHK Flat in Sohna,flat,signature global park,0.54,7200.0,750.0,Carpet area: 750 (69.68 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",4.0,North-East,Under Construction,"['Sector 55-56 metro', 'Global city centre', '...",Fourth floor with 100% roof rights.One covered...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Management4 out of 5', 'Green Area5 out of 5..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,1.85,8078.0,2290.0,Super Built up area 2290(212.75 sq.m.),3,4,3+,"servant room,study room,pooja room,store room","1245, Sector 104 Gurgaon, Gurgaon, Haryana",14.0,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,"['7 Fan', '7 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
3,2 BHK Flat in Sector 99A Gurgaon,flat,pareena laxmi apartments,0.32,6106.0,524.0,Super Built up area 524(48.68 sq.m.)Carpet are...,2,2,2,not available,"Sector 99A Gurgaon, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Dwarka Expy', 'Govt. Sr. Sec. School', 'Exce...",This lovely 2 bhk apartment/flat in sector 99a...,[],"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Green Area4.5 out of 5', 'Amenities3.5 out o..."
4,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.40,5929.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,0,not available,"A02/101 2361sq Ft, Sector 107 Gurgaon, Gurgaon...",1.0,East,0 to 1 Year Old,NaN,Looking for a good 3 bhk apartment in sector 1...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety1 out of 5', 'Lifestyle2 out of 5', 'E..."

In [173]:
df.shape

(3961, 20)

In [174]:
df.duplicated().sum()

np.int64(0)

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price_in_crore   3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [176]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price_in_crore       20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [177]:
df.head(100)

,property_name,property_type,society,price_in_crore,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 56 Gurgaon,flat,smriti apartment,0.45,7500.0,600.0,Super Built up area 600(55.74 sq.m.),1,1,2,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",3.0,NaN,10+ Year Old,"['Sector 54 chowk metro station', 'Sector metr...",Gated society.\n4th floor.\nJust 400 meters fr...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
1,2 BHK Flat in Sohna,flat,signature global park,0.54,7200.0,750.0,Carpet area: 750 (69.68 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",4.0,North-East,Under Construction,"['Sector 55-56 metro', 'Global city centre', '...",Fourth floor with 100% roof rights.One covered...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Management4 out of 5', 'Green Area5 out of 5..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,1.85,8078.0,2290.0,Super Built up area 2290(212.75 sq.m.),3,4,3+,"servant room,study room,pooja room,store room","1245, Sector 104 Gurgaon, Gurgaon, Haryana",14.0,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,"['7 Fan', '7 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
3,2 BHK Flat in Sector 99A Gurgaon,flat,pareena laxmi apartments,0.32,6106.0,524.0,Super Built up area 524(48.68 sq.m.)Carpet are...,2,2,2,not available,"Sector 99A Gurgaon, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Dwarka Expy', 'Govt. Sr. Sec. School', 'Exce...",This lovely 2 bhk apartment/flat in sector 99a...,[],"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Green Area4.5 out of 5', 'Amenities3.5 out o..."
4,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.40,5929.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,0,not available,"A02/101 2361sq Ft, Sector 107 Gurgaon, Gurgaon...",1.0,East,0 to 1 Year Old,NaN,Looking for a good 3 bhk apartment in sector 1...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety1 out of 5', 'Lifestyle2 out of 5', 'E..."
5,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,6.25,11574.0,5400.0,Plot area 600(501.68 sq.m.),4,4,3+,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",600 sqyard upper duplex - 4 bhk + servant + 02...,"['1 Exhaust Fan', '5 Geyser', '7 AC', 'No Bed'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
6,4 Bedroom House for sale in Dhankot,house,independent,0.70,9722.0,720.0,Plot area 80(66.89 sq.m.),4,3,2,"pooja room,store room","Dhankot, Gurgaon, Haryana",3.0,West,1 to 5 Year Old,NaN,Ground floor tuition center with computer lab ...,"['1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Ligh...","['Feng Shui / Vaastu Compliant', 'Water Storage']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
7,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.30,4545.0,2860.0,Super Built up area 2860(265.7 sq.m.),3,3,1,not available,NaN,6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...","A 3 bhk flat in sector-83, gurgaon is availabl...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
8,5 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,11.75,23240.0,5056.0,Plot area 502(419.74 sq.m.),5,7,3+,servant room,"A-6, Sector 33 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",520 sqyd 5bhk villa available for sale at unit...,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Safety4 out of 5', ..."
9,3 BHK Flat in Sector 108 Gurgaon,flat,raheja vedaanta,1.25,5681.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,2,0,not available,"Sector 108 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,NaN,Residential apartment for sell.Located on grou...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management3 out of 5', 'Green Area4 out of 5..."
10,3 BHK Flat in Nirvana Country,flat,the close north,2.92,11209.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,servant room,"1002, Nirvana Country, Gurgaon, Haryana",10.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",Looking for a 3 bhk property for sale in gurga...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
11,5 Bedroom House for sale in Laxman Vihar,house,independent,0.50,10482.0,477.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
12,2 BHK Flat in Palam Vihar,flat,bestech park view residency,1.02,7208.0,1415.0,Super Built up area 1415(131.46 sq.m.),2,2,3,not available,"Palam Vihar, Gurgaon, Haryana",11.0,South-West,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Looking for a 2 bhk property for sale in gurga...,"['2 Wardrobe', '4 Fan', '1 Geyser', '4 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."
13,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,not available,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
14,2 BHK Flat in Sector 108 Gurgaon,flat,sobha city,2.40,17378.0,1381.0,Super Built up area 1381(128.3 sq.m.),2,2,2,not available,"Sector 108 Gurgaon, Gurgaon, Haryana",14.0,NaN,0 to 1 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Price completely non-Negotiable. Interior work...,"['4 Fan', '2 Geyser', '4 Light', '1 AC', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
15,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
16,3 Bedroom House for sale in Ansal Plaza,house,independent,2.40,12000.0,2000.0,Plot area 2000(185.81 sq.m.),3,3,2,"store room,pooja room","Ansal Plaza, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Wishing to settle down in an individual house ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
17,4 Bedroom House for sale in Sector 4 Gurgaon,house,independent,2.30,17014.0,1352.0,Plot area 160(133.78 sq.m.),4,4,3,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",Kothi for sale in sector 4 gurgaon at an very ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Park', 'Visitor Parking', 'Club house / Comm...","['Environment5 out of 5', 'Safety5 out of 5', ..."
18,4 BHK Flat in Sector 92 Gurgaon,flat,sare homes,0.80,4694.0,1704.0,Carpet area: 1704 (158.31 sq.m.),4,4,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",1.0,North-East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Beautiful, spacious 4bed 4 bath with closed pa...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 AC...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
19,2 BHK Flat in Sector 70A Gurgaon,flat,capital residences 360,1.10,7586.0,1450.0,Super Built up area 1450(134.71 sq.m.),2,2,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",8.0,NaN,0 to 1 Year Old,NaN,"Address: 1st floor, sector 70a gurgaon, gurgao...","['2 Geyser', '3 AC', 'No Bed', 'No Chimney', '...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
20,3 BHK Flat in Sector 59 Gurgaon,flat,conscient elevate,4.02,17500.0,2297.0,Carpet area: 2295 (213.21 sq.m.),3,3,1,not available,"Sector 59 Gurgaon, Gurgaon, Haryana",3.0,NaN,By 2024,"['Rapid Metro Station Sector 55', 'Paras Trini...",Conscient elevate offers residential apartment...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...",NaN
21,2 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,2.80,11470.0,2441.0,Super Built up area 2441(226.78 sq.m.)Built Up...,2,3,2,"study room,servant room","Sector 112 Gurgaon, Gurgaon, Haryana",9.0,South-East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Spacious 2 bhk study servant is available for ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
22,5 Bedroom House for sale in B Block Sushant Lo...,house,independent,15.50,28233.0,5490.0,Plot area 610(510.04 sq.m.),5,6,3,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
23,3 BHK Flat in Sector 89 Gurgaon,flat,nbcc heights,1.50,7058.0,2125.0,Super Built up area 2125(197.42 sq.m.),3,3,3,"study room,servant room","D-801, Sector 89 Gurgaon, Gurgaon, Haryana",8.0,NaN,1 to 5 Year Old,"['Reliance MART', 'Lotus Rise World School', '...","Ready to move, auspicious property. Only serio...","['4 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
24,4 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.78,8036.0,2215.0,Super Built up area 2215(205.78 sq.m.)Built Up...,4,4,3+,not available,"Sector 90 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal gardens is one of gurgaon's most sou...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
25,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.24,7065.0,1755.0,Super Built up area 1755(163.04 sq.m.)Built Up...,3,3,3+,others,"Top Floor, Sector 90 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal garden sector 90Ready to move in pro...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
26,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,2.34,11185.0,2092.0,Super Built up area 2092(194.35 sq.m.)Built Up...,3,4,3+,servant room,"N151, Sector 81 Gurgaon, Gurgaon, Haryana",14.0,South-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","This 3 bhk flat is located in dlf the ultima, ...","['7 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
27,4 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,3.50,21605.0,1620.0,Plot area 180(150.5 sq.m.),4,4,2,pooja room,"Sector 46 Gurgaon, Gurgaon, Haryana",2.0,South-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",4bhk independent house is for sale in gurgaon ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['High Ceiling Height', 'Water Storage', 'Park...","['Environment4 out of 5', 'Safety4 out of 5', ..."
28,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,1.62,9380.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,store room,"000, Sector 67A Gurgaon, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +store room resid...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
29,3 BHK Flat in Palam Vihar,flat,bestech park view residency,1.59,8281.0,1920.0,Super Built up area 1920(178.37 sq.m.),3,4,3+,servant room,"Palam Vihar, Gurgaon, Haryana",11.0,North-West,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Located in the popular residential address of ...,"['3 Wardrobe', '4 Fan', '1 Geyser', '5 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."
30,4 Bedroom House for sale in Sector 48 Gurgaon,house,independent,5.50,23504.0,2340.0,Plot area 260(217.39 sq.m.),4,4,2,servant room,"Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",This property is located in sector 48. It's 4b...,"['4 Wardrobe', '8 Fan', '5 Geyser', '16 Light'...","['Water Storage', 'Park', 'Piped-gas', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."
31,4 BHK Flat in Sector 38 Gurgaon,flat,navjyoti apartment,2.10,11938.0,1759.0,Carpet area: 1759 (163.42 sq.m.),4,4,3+,not available,"Sector 38 Gurgaon, Gurgaon, Haryana",10.0,North,10+ Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...",Navjyoti apartment is one of the most popular ...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Maintenance Staff', 'Visitor Park...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
32,2 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,0.38,6919.0,549.0,Carpet area: 549.17 (51.02 sq.m.),2,2,1,not available,"E-404, Sector 95 Gurgaon, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Mall facing -Corner flat.4th floor with best c...,[],NaN,"['Safety4.5 out of 5', 'Lifestyle4.5 out of 5'..."
33,3 BHK Flat in Sector 37C Gurgaon,flat,imperia the esfera,0.99,5454.0,1815.0,Super Built up area 1815(168.62 sq.m.)Carpet a...,3,4,3,servant room,"Sector 37C Gurgaon, Gurgaon, Haryana",9.0,North-East,1 to 5 Year Old,"['Approved Sector 37 Mero Station', 'Esplanade...",Located in the popular residential address of ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
34,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.80,8215.0,2191.0,Super Built up area 2191(203.55 sq.m.),4,3,3,study room,"Tower 21, Sector 37D Gurgaon, Gurgaon, Haryana",12.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","Bptp terra - Sector 37d, gurgaon Ready to move...","['5 Fan', '1 Stove', '6 Light', '6 AC', '1 Mod...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
35,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,1.15,5808.0,1980.0,Super Built up area 1980(183.95 sq.m.)Built Up...,3,3,2,"pooja room,store room,study room,servant room","102, Sector 83 Gurgaon, Gurgaon, Haryana",3.0,South,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Luxurious 3 bhk apartment for rent in sector-8...,"['5 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
36,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,2.99,14950.0,2000.0,Super Built up area 2000(185.81 sq.m.)Built Up...,3,3,3,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",We deal exclusively in palm drive,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
37,2 BHK Flat in Sector 106 Gurgaon,flat,paras dews,0.97,8818.0,1100.0,Super Built up area 1385(128.67 sq.m.)Built Up...,2,2,3,pooja room,"1201, Sector 106 Gurgaon, Gurgaon, Haryana",6.0,North-East,0 to 1 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Looking for a 2 bhk property for sale in gurga...,"['4 Fan', '1 Exhaust Fan', '1 Stove', '5 Light...","['Centrally Air Conditioned', 'Water purifier'...",NaN
38,7 Bedroom House for sale in Sector 5 Gurgaon,house,sheetla enclave,0.96,10000.0,960.0,Plot area 945(87.79 sq.m.),7,4,2,"pooja room,store room","House No 8, Sector 5 Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",It is very near to all the important places li...,"['1 Wardrobe', '1 Water Purifier', '1 Fan', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
39,4 BHK Flat in Sector 106 Gurgaon,flat,paras dews,1.35,8940.0,1510.0,Carpet area: 1510 (140.28 sq.m.),4,3,3,servant room,"1901, Sector 106 Gurgaon, Gurgaon, Haryana",19.0,NaN,10+ Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Check out this 4 bhk apartment for sale in par...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...",NaN
40,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,12.00,38095.0,3150.0,Plot area 350(292.64 sq.m.),5,6,3+,"store room,servant room","Sector 66 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Looking to buy an independent house in gurgaon...,"['1 Exhaust Fan', '8 AC', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
41,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,0.95,4856.0,1956.0,Super Built up area 1956(181.72 sq.m.),4,3,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",4.0,North,5 to 10 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Ready to move in property.\nHealth and educati...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
42,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,3.99,12912.0,3090.0,Super Built up area 3090(287.07 sq.m.),3,5,3+,servant room,"Jwala Mill Road, Sector 22 Gurgaon, Gurgaon, H...",3.0,NaN,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Residential apartment for sell.The property ha...,"['1 Fridge', '1 Exhaust Fan', '4 Geyser', '1 W...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
43,3 BHK Flat in Dwarka Expressway Gurgaon,flat,hero homes,1.60,7825.0,2045.0,Super Built up area 1689(156.91 sq.m.),3,3,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Gol Market', 'Gurdwara Baba Deep Singh', 'Gu...",We are the proud owners of this 3 bhk apartmen...,"['2 Wardrobe', '2 Fan', '2 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
44,3 BHK Flat in Sector 37D Gurgaon,flat,ramprastha the atrium,1.00,7782.0,1285.0,Super Built up area 1285(119.38 sq.m.),3,3,2,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",4.0,NaN,1 to 5 Year Old,"['Dwarka Expressway', 'Delhi Jaipur Highway', ...",Wood work in all 3 rooms. \nModular kitchen wi...,"['1 Exhaust Fan', '1 Modular Kitchen', '1 Chim...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'P...","['Management4 out of 5', 'Green Area5 out of 5..."

In [178]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [179]:
df.head(100)

,property_name,property_type,society,sector,price_in_crore,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,1 BHK Flat in Sector 56 Gurgaon,flat,smriti apartment,Sector 56,0.45,7500.0,600.0,Super Built up area 600(55.74 sq.m.),1,1,2,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",3.0,NaN,10+ Year Old,"['Sector 54 chowk metro station', 'Sector metr...",Gated society.\n4th floor.\nJust 400 meters fr...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
1,2 BHK Flat in Sohna,flat,signature global park,Sohna,0.54,7200.0,750.0,Carpet area: 750 (69.68 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",4.0,North-East,Under Construction,"['Sector 55-56 metro', 'Global city centre', '...",Fourth floor with 100% roof rights.One covered...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Management4 out of 5', 'Green Area5 out of 5..."
2,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,Sector 104,1.85,8078.0,2290.0,Super Built up area 2290(212.75 sq.m.),3,4,3+,"servant room,study room,pooja room,store room","1245, Sector 104 Gurgaon, Gurgaon, Haryana",14.0,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...",Ats triumph is one of gurgaon's most sought af...,"['7 Fan', '7 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
3,2 BHK Flat in Sector 99A Gurgaon,flat,pareena laxmi apartments,Sector 99A,0.32,6106.0,524.0,Super Built up area 524(48.68 sq.m.)Carpet are...,2,2,2,not available,"Sector 99A Gurgaon, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Dwarka Expy', 'Govt. Sr. Sec. School', 'Exce...",This lovely 2 bhk apartment/flat in sector 99a...,[],"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Green Area4.5 out of 5', 'Amenities3.5 out o..."
4,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,Sector 107,1.40,5929.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,0,not available,"A02/101 2361sq Ft, Sector 107 Gurgaon, Gurgaon...",1.0,East,0 to 1 Year Old,NaN,Looking for a good 3 bhk apartment in sector 1...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety1 out of 5', 'Lifestyle2 out of 5', 'E..."
5,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,Sector 109,6.25,11574.0,5400.0,Plot area 600(501.68 sq.m.),4,4,3+,servant room,"Sector 109 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",600 sqyard upper duplex - 4 bhk + servant + 02...,"['1 Exhaust Fan', '5 Geyser', '7 AC', 'No Bed'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
6,4 Bedroom House for sale in Dhankot,house,independent,Dhankot,0.70,9722.0,720.0,Plot area 80(66.89 sq.m.),4,3,2,"pooja room,store room","Dhankot, Gurgaon, Haryana",3.0,West,1 to 5 Year Old,NaN,Ground floor tuition center with computer lab ...,"['1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Ligh...","['Feng Shui / Vaastu Compliant', 'Water Storage']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
7,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,Sector 83,1.30,4545.0,2860.0,Super Built up area 2860(265.7 sq.m.),3,3,1,not available,NaN,6.0,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...","A 3 bhk flat in sector-83, gurgaon is availabl...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4 out ..."
8,5 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,Sector 33,11.75,23240.0,5056.0,Plot area 502(419.74 sq.m.),5,7,3+,servant room,"A-6, Sector 33 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",520 sqyd 5bhk villa available for sale at unit...,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Safety4 out of 5', ..."
9,3 BHK Flat in Sector 108 Gurgaon,flat,raheja vedaanta,Sector 108,1.25,5681.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,2,0,not available,"Sector 108 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,NaN,Residential apartment for sell.Located on grou...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management3 out of 5', 'Green Area4 out of 5..."
10,3 BHK Flat in Nirvana Country,flat,the close north,Nirvana Country,2.92,11209.0,2605.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,servant room,"1002, Nirvana Country, Gurgaon, Haryana",10.0,North,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...",Looking for a 3 bhk property for sale in gurga...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
11,5 Bedroom House for sale in Laxman Vihar,house,independent,Laxman Vihar,0.50,10482.0,477.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
12,2 BHK Flat in Palam Vihar,flat,bestech park view residency,Palam Vihar,1.02,7208.0,1415.0,Super Built up area 1415(131.46 sq.m.),2,2,3,not available,"Palam Vihar, Gurgaon, Haryana",11.0,South-West,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Looking for a 2 bhk property for sale in gurga...,"['2 Wardrobe', '4 Fan', '1 Geyser', '4 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."
13,2 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one,Sector 95,0.55,5556.0,990.0,Built Up area: 990 (91.97 sq.m.)Carpet area: 9...,2,2,3,not available,"Sector 95,gurgaon, Sector 95 Gurgaon, Gurgaon,...",15.0,North-East,undefined,NaN,"2 bath, semi-Furnished, 15th floor (Of 20), ov...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4.5 out of 5'..."
14,2 BHK Flat in Sector 108 Gurgaon,flat,sobha city,Sector 108,2.40,17378.0,1381.0,Super Built up area 1381(128.3 sq.m.),2,2,2,not available,"Sector 108 Gurgaon, Gurgaon, Haryana",14.0,NaN,0 to 1 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Price completely non-Negotiable. Interior work...,"['4 Fan', '2 Geyser', '4 Light', '1 AC', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
15,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,New Palam Vihar,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
16,3 Bedroom House for sale in Ansal Plaza,house,independent,Ansal Plaza,2.40,12000.0,2000.0,Plot area 2000(185.81 sq.m.),3,3,2,"store room,pooja room","Ansal Plaza, Gurgaon, Haryana",2.0,North-East,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Wishing to settle down in an individual house ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
17,4 Bedroom House for sale in Sector 4 Gurgaon,house,independent,Sector 4,2.30,17014.0,1352.0,Plot area 160(133.78 sq.m.),4,4,3,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",Kothi for sale in sector 4 gurgaon at an very ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Park', 'Visitor Parking', 'Club house / Comm...","['Environment5 out of 5', 'Safety5 out of 5', ..."
18,4 BHK Flat in Sector 92 Gurgaon,flat,sare homes,Sector 92,0.80,4694.0,1704.0,Carpet area: 1704 (158.31 sq.m.),4,4,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",1.0,North-East,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Beautiful, spacious 4bed 4 bath with closed pa...","['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 AC...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
19,2 BHK Flat in Sector 70A Gurgaon,flat,capital residences 360,Sector 70A,1.10,7586.0,1450.0,Super Built up area 1450(134.71 sq.m.),2,2,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",8.0,NaN,0 to 1 Year Old,NaN,"Address: 1st floor, sector 70a gurgaon, gurgao...","['2 Geyser', '3 AC', 'No Bed', 'No Chimney', '...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
20,3 BHK Flat in Sector 59 Gurgaon,flat,conscient elevate,Sector 59,4.02,17500.0,2297.0,Carpet area: 2295 (213.21 sq.m.),3,3,1,not available,"Sector 59 Gurgaon, Gurgaon, Haryana",3.0,NaN,By 2024,"['Rapid Metro Station Sector 55', 'Paras Trini...",Conscient elevate offers residential apartment...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...",NaN
21,2 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,Sector 112,2.80,11470.0,2441.0,Super Built up area 2441(226.78 sq.m.)Built Up...,2,3,2,"study room,servant room","Sector 112 Gurgaon, Gurgaon, Haryana",9.0,South-East,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Spacious 2 bhk study servant is available for ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
22,5 Bedroom House for sale in B Block Sushant Lo...,house,independent,B Block Sushant Lok Phase 1,15.50,28233.0,5490.0,Plot area 610(510.04 sq.m.),5,6,3,"pooja room,study room,servant room,store room","B Block Sushant Lok Phase 1, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...","Basement , ground floor, first floor and terra...",[],"['Private Garden / Terrace', 'Water purifier',...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
23,3 BHK Flat in Sector 89 Gurgaon,flat,nbcc heights,Sector 89,1.50,7058.0,2125.0,Super Built up area 2125(197.42 sq.m.),3,3,3,"study room,servant room","D-801, Sector 89 Gurgaon, Gurgaon, Haryana",8.0,NaN,1 to 5 Year Old,"['Reliance MART', 'Lotus Rise World School', '...","Ready to move, auspicious property. Only serio...","['4 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
24,4 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,Sector 90,1.78,8036.0,2215.0,Super Built up area 2215(205.78 sq.m.)Built Up...,4,4,3+,not available,"Sector 90 Gurgaon, Gurgaon, Haryana",8.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal gardens is one of gurgaon's most sou...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
25,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,Sector 90,1.24,7065.0,1755.0,Super Built up area 1755(163.04 sq.m.)Built Up...,3,3,3+,others,"Top Floor, Sector 90 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Dlf regal garden sector 90Ready to move in pro...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
26,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,Sector 81,2.34,11185.0,2092.0,Super Built up area 2092(194.35 sq.m.)Built Up...,3,4,3+,servant room,"N151, Sector 81 Gurgaon, Gurgaon, Haryana",14.0,South-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","This 3 bhk flat is located in dlf the ultima, ...","['7 Fan', '1 Fridge', '1 Exhaust Fan', '4 Geys...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
27,4 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,Sector 46,3.50,21605.0,1620.0,Plot area 180(150.5 sq.m.),4,4,2,pooja room,"Sector 46 Gurgaon, Gurgaon, Haryana",2.0,South-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",4bhk independent house is for sale in gurgaon ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['High Ceiling Height', 'Water Storage', 'Park...","['Environment4 out of 5', 'Safety4 out of 5', ..."
28,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,Sector 67A,1.62,9380.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,store room,"000, Sector 67A Gurgaon, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +store room resid...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
29,3 BHK Flat in Palam Vihar,flat,bestech park view residency,Palam Vihar,1.59,8281.0,1920.0,Super Built up area 1920(178.37 sq.m.),3,4,3+,servant room,"Palam Vihar, Gurgaon, Haryana",11.0,North-West,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Located in the popular residential address of ...,"['3 Wardrobe', '4 Fan', '1 Geyser', '5 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."
30,4 Bedroom House for sale in Sector 48 Gurgaon,house,independent,Sector 48,5.50,23504.0,2340.0,Plot area 260(217.39 sq.m.),4,4,2,servant room,"Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",This property is located in sector 48. It's 4b...,"['4 Wardrobe', '8 Fan', '5 Geyser', '16 Light'...","['Water Storage', 'Park', 'Piped-gas', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."
31,4 BHK Flat in Sector 38 Gurgaon,flat,navjyoti apartment,Sector 38,2.10,11938.0,1759.0,Carpet area: 1759 (163.42 sq.m.),4,4,3+,not available,"Sector 38 Gurgaon, Gurgaon, Haryana",10.0,North,10+ Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...",Navjyoti apartment is one of the most popular ...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Lift(s)', 'Maintenance Staff', 'Visitor Park...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
32,2 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,Sector 95,0.38,6919.0,549.0,Carpet area: 549.17 (51.02 sq.m.),2,2,1,not available,"E-404, Sector 95 Gurgaon, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Mall facing -Corner flat.4th floor with best c...,[],NaN,"['Safety4.5 out of 5', 'Lifestyle4.5 out of 5'..."
33,3 BHK Flat in Sector 37C Gurgaon,flat,imperia the esfera,Sector 37C,0.99,5454.0,1815.0,Super Built up area 1815(168.62 sq.m.)Carpet a...,3,4,3,servant room,"Sector 37C Gurgaon, Gurgaon, Haryana",9.0,North-East,1 to 5 Year Old,"['Approved Sector 37 Mero Station', 'Esplanade...",Located in the popular residential address of ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
34,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,Sector 37D,1.80,8215.0,2191.0,Super Built up area 2191(203.55 sq.m.),4,3,3,study room,"Tower 21, Sector 37D Gurgaon, Gurgaon, Haryana",12.0,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","Bptp terra - Sector 37d, gurgaon Ready to move...","['5 Fan', '1 Stove', '6 Light', '6 AC', '1 Mod...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
35,3 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,Sector 83,1.15,5808.0,1980.0,Super Built up area 1980(183.95 sq.m.)Built Up...,3,3,2,"pooja room,store room,study room,servant room","102, Sector 83 Gurgaon, Gurgaon, Haryana",3.0,South,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Luxurious 3 bhk apartment for rent in sector-8...,"['5 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
36,3 BHK Flat in Sector 66 Gurgaon,flat,emaar mgf the palm drive,Sector 66,2.99,14950.0,2000.0,Super Built up area 2000(185.81 sq.m.)Built Up...,3,3,3,servant room,"Sector 66 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",We deal exclusively in palm drive,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4.5 out ..."
37,2 BHK Flat in Sector 106 Gurgaon,flat,paras dews,Sector 106,0.97,8818.0,1100.0,Super Built up area 1385(128.67 sq.m.)Built Up...,2,2,3,pooja room,"1201, Sector 106 Gurgaon, Gurgaon, Haryana",6.0,North-East,0 to 1 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Looking for a 2 bhk property for sale in gurga...,"['4 Fan', '1 Exhaust Fan', '1 Stove', '5 Light...","['Centrally Air Conditioned', 'Water purifier'...",NaN
38,7 Bedroom House for sale in Sector 5 Gurgaon,house,sheetla enclave,Sector 5,0.96,10000.0,960.0,Plot area 945(87.79 sq.m.),7,4,2,"pooja room,store room","House No 8, Sector 5 Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",It is very near to all the important places li...,"['1 Wardrobe', '1 Water Purifier', '1 Fan', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
39,4 BHK Flat in Sector 106 Gurgaon,flat,paras dews,Sector 106,1.35,8940.0,1510.0,Carpet area: 1510 (140.28 sq.m.),4,3,3,servant room,"1901, Sector 106 Gurgaon, Gurgaon, Haryana",19.0,NaN,10+ Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Check out this 4 bhk apartment for sale in par...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...",NaN
40,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,Sector 66,12.00,38095.0,3150.0,Plot area 350(292.64 sq.m.),5,6,3+,"store room,servant room","Sector 66 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Looking to buy an independent house in gurgaon...,"['1 Exhaust Fan', '8 AC', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
41,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,Sector 92,0.95,4856.0,1956.0,Super Built up area 1956(181.72 sq.m.),4,3,3,not available,"Sector 92 Gurgaon, Gurgaon, Haryana",4.0,North,5 to 10 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Ready to move in property.\nHealth and educati...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
42,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,Sector 22,3.99,12912.0,3090.0,Super Built up area 3090(287.07 sq.m.),3,5,3+,servant room,"Jwala Mill Road, Sector 22 Gurgaon, Gurgaon, H...",3.0,NaN,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Residential apartment for sell.The property ha...,"['1 Fridge', '1 Exhaust Fan', '4 Geyser', '1 W...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
43,3 BHK Flat in Dwarka Expressway Gurgaon,flat,hero homes,Dwarka Expressway,1.60,7825.0,2045.0,Super Built up area 1689(156.91 sq.m.),3,3,3,not available,"Dwarka Expressway Gurgaon, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Gol Market', 'Gurdwara Baba Deep Singh', 'Gu...",We are the proud owners of this 3 bhk apartmen...,"['2 Wardrobe', '2 Fan', '2 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN

In [180]:
df['sector'] = df['sector'].str.lower()

In [181]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 81                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 14                                                     15
sector 60                                                     15
sector 63                                                     15
sector 76                                                     14
gwal pahari                                                   14
sector 53                                                     14
dlf phase 5                                                   14
sector 52                                                     14
sector 3                                                      14
sector 1 imt manesar                                          14
rajendra park                                                 14
sector 36a                                                    13
sector 46                                                     13
laxman vihar phase 2                                          13
sector 93                                                     12
uppals southend                                               12
sohna road                                                    12
sector 39                                                     12
sector 31                                                     12
sector 50                                                     12
sector 38                                                     12
sector 47                                                     11
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 4                                                       9
south city 1                                                   9
sector 95a                                                     9
sector 55                                                      9
ashok vihar phase 2                                            9
sector 57                                                      8
sector 59                                                      8
dwarka expressway                                              8
palam vihar extension                                          8
sector 40                                                      8
mehrauli  road                                                 8
c block sushant lok phase 1                                    8
sector 43                                                      8
sector 89 a                                                    8
malibu town                                                    8
sector 10a                                                     8
sector 11                                                      7
sector 51                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
sector 26                                                      7
new colony                                                     7
sector 58                                                      7
surat nagar 1                                                  7
rajiv nagar                                                    6
jacobpura                                                      6
jyoti park                                                     6
sector 1                                                       6
ashok vihar                                                    6
sector 5                                                       6
arjun nagar                                                    5
greenwood city                                                 5
saraswati vihar                                                5
new palam vihar                                                5
chakkarpur                                                     5
subhash nagar                                                  5
ansal plaza                                                    5
sector 105                                                     5
sector 28                                                      5
sector 23a                                                     5
manesar                                                        5
sector 2                                                       5
dayanand colony                                                5
sushant lok phase 2                                            5
sector 80                                                      5
sector 30                                                      5
sector 9                                                       5
valley view estate                                             4
new                                                            4
surya vihar                                                    4
adarsh nagar                                                   4
krishna colony                                                 4
sector 12a                                                     4
vishnu garden                                                  4
ravi nagar                                                     4
shivpuri                                                       4
bhim nagar                                                     4
sector 45                                                      4
sector 3a                                                      4
sector 36                                                      4
bhondsi                                                        4
sector 17                                                      4
garhi harsaru                                                  4
sector 12                                                      4
madanpuri                                                      4
dharam colony                                                  4
suncity                                                        4
baldev nagar                                                   4
shivaji nagar                                                  4
devilal colony                                                 4
imt manesar                                                    4
sector 6                                                       4
sector 8                                                       3
sector 110 a                                                   3
gandhi nagar                                                   3
sector 15                                                      3
sector 27                                                      3
sector 17a                                                     3
sector 88b                                                     3
sector 73                                                      3
shakti nagar                                                   3
a block sushant lok phase 1                                    3
mg road                                                        3
patel nagar                                                    3
sector 23                                                      3
sector 17b                                                     3
prem nagar                                                     3
maruti kunj                                                    3
b block sushant lok phase 1                                    3
laxmi garden                                                   3
sector 21                                                      2
west rajiv nagar                                               2
iffco chowk                                                    2
new palam vihar phase 1                                        2
, delhi ncr                                                    2
golf course ext road                                           2
sushant lok                                                    2
nars                                                           2
sector 15 part 1                                               2
rajiv chowk                                                    2
sector 41                                                      2
shanti nagar                                                   2
sector 15 part 2                                               2
lajpat nagar                                                   2
mayfield garden                                                2
sector-11 sohna                                                2
new basti                                                      2
pratap nagar                                                   2
sector 32                                                      2
rosewood                                                       2
golf course road                                               2
shankar vihar                                                  2
sector-2 sohna                                                 2
block a surya vihar                                            2
manohar nagar                                                  2
farukhnagar                                                    2
mohan nagar                                                    2
sispal vihar                                                   2
surat nagar phase 2                                            2
bissar                                                         2
samaspur                                                       2
ambience island                                                2
hira nagar                                                     2
surat nagar                                                    2
sheetla colony                                                 2
bhawani enclave                                                2
daulatabad                                                     2
faridabad road                                                 2
sohna  road                                                    2
sector 24                                                      2
new palam vihar phase 2                                        2
acharya puri                                                   2
sector 4 urban estate                                          1
sector 5 chowk                                                 1
dhankot                                                        1
alipur                                                         1
near sector 1 market                                           1
sector-5 sheetla colony                                        1
sector 42                                                      1
shivji park colony                                             1
damdma                                                         1
sai kunj                                                       1
old delhi road, opp sector-14                                  1
sadar bazar                                                    1
urban estate, sector 5                                         1
new colony, sector 7                                           1
nirvana country pocket h                                       1
sector 13                                                      1
bhimgarh kheri phase 3                                         1
sultanpur                                                      1
gopal nagar, garhi ghasita, sonipat                            1
pataudi road                                                   1
v block dlf phase 3                                            1
civil l                                                        1
ravi nager basai road                                          1
laxmna vihar, phase 2                                          1
khandsa                                                        1
sector 21a faridabad                                           1
ats marigold                                                   1
block g sector-57                                              1
heritage city                                                  1
mahavir pura                                                   1
om nagar                                                       1
udyog vihar phase 1                                            1
south city                                                     1
rattan garden                                                  1
sector 37b                                                     1
near nand hospital                                             1
carterpuri village                                             1
jacobpura near sadar bazar                                     1
ashok vihar phase 3                                            1
saraswati enclave                                              1
kheri                                                          1
vir nagar                                                      1
sector-35 sohna                                                1
sec 3 bhim vihar part 1 bhimgher kheri                         1
park view                                                      1
block h ashok vihar phase iii extension                        1
g block dlf city phase 1                                       1
sector 17c                                                     1
laxman vihar, railway road,                                    1
bhora kalan                                                    1
part 3 sector 5                                                1
near euro                                                      1
ashok vihar phase i                                            1
near khandsa road                                              1
near pataudi chowk                                             1
b1 block sector 57                                             1
anand garden, sector-105                                       1
kanahi                                                         1
hsiidc plot sector 1 imt manesar                               1
begampur khatola                                               1
cyber city                                                     1
rajiv colony                                                   1
new jyoti park                                                 1
sector 9b                                                      1
godrej aria , sector 79 ,                                      1
saroop garden rajendra park                                    1
hno 13 sagar enclave sura                                      1
huda saraswati vihar                                           1
lucknow                                                        1
jat colony,fazilpur/taj nagar road                             1
sector-5 sohna                                                 1
naharpur rupa                                                  1
ram nagar                                                      1
mahalaxmi garden, rajendra place                               1
devi lal colony gali no 12 gurgaon nr omkar public school      1
ansal's palam vihar                                            1
bptp                                                           1
garauli kalan                                                  1
sector 37a                                                     1
tekchand nagar                                                 1
sector-7 hous                                                  1
Name: count, dtype: int64

In [182]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [183]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [184]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [185]:
df['sector'].unique()

array(['sector 56', 'sohna road', 'sector 104', 'sector 99a',
       'sector 107', 'sector 109', 'dhankot', 'sector 83', 'sector 33',
       'sector 108', 'sector 50', 'sector 4', 'sector 2', 'sector 95',
       'new sector 2', 'sector 23', 'sector 92', 'sector 70a',
       'sector 59', 'sector 112', 'b block sector 43', 'sector 89',
       'sector 90', 'sector 81', 'sector 46', 'sector 67a', 'sector 48',
       'sector 38', 'sector 37c', 'sector 37d', 'sector 66', 'sector 106',
       'sector 5', 'sector 22', 'dwarka expressway', 'sector 1 manesar',
       'sector 79', 'sector 102', 'sector 3 phase 2', 'sector 4 phase 2',
       'sector 24', 'sector 7', 'sector 60', 'sector 91', 'sector 57',
       'sector 111', 'sector 77', 'sector 52', 'sector 63', 'sector 69',
       'sector 85', 'sector 70', 'sector 68', 'sector 61', 'sector 84',
       'sector 2 extension', 'sector-33 sohna road', 'sector 40',
       'sector 17', 'rattan garden', 'sector 103', 'sector 6',
       'sector 3 phase 3 extension', 'manohar nagar', 'sector 62',
       'sector 49', 'sector 28', 'sector 54', 'sector 11', 'sector 43',
       'sector 105', 'a block sector 43', 'c block sector 43',
       'sector 113', 'sector 47', 'sector 73', 'new basti', 'sector 9',
       'gwal pahari', 'sector 82a', 'sector 26', 'sector 13', 'sector 86',
       'shankar vihar', 'sector 12', 'sector 82', 'sector 51',
       'sector 25', 'sector 3', 'sector 88a', 'sector-5 sheetla colony',
       'sector 71', 'sector 65', 'sector 72', 'sector 8', 'sector 10a',
       'sector 39', 'sector 99', 'sector 1', 'sector 36 sohna road',
       'sector 53', 'sector 67', 'bhimgarh kheri phase 3',
       'sector 50 pocket h', 'block a sector 21', 'sector 14',
       'sector 78', 'sector 12a', 'sector 9a', 'sector 63a',
       'surat nagar phase 2', 'sector 95a', 'sector 74', 'sector 17a',
       'golf course road', 'rosewood', 'sector 93', 'sector 1a manesar',
       'sector 41', 'farukhnagar', 'sector 88b', 'sector 21',
       'mohan nagar', 'new', 'sector 27', 'sector-11 sohna road',
       'sohna road road', 'gopal nagar, garhi ghasita, sonipat',
       'sector 36a', 'pratap nagar', 'manesar', 'sultanpur', 'sector 32',
       'sector 37b', 'sector 89 a', 'sector 110', 'sector 17b',
       'heritage city', 'sector 30', 'block g sector-57', 'sector 36',
       'ats marigold', 'sector 45', 'sector 21a faridabad',
       'acharya puri', 'sector 110 a', 'sector 55', 'om nagar',
       'mahavir pura', 'sector 31', 'sohna road  road', 'sector 15',
       'udyog vihar phase 1', 'sector 76', 'maruti kunj', 'sector 80',
       'south city', 'ravi nager basai road', 'daulatabad',
       'new sector 2 phase 2', 'faridabad road', 'laxmna vihar, phase 2',
       'nars', 'samaspur', 'bhawani enclave', 'sushant lok', 'khandsa',
       'v block sector 24', 'sector 15 part 1', 'sheetla colony',
       'sector 12 near sadar bazar', 'iffco chowk', 'near nand hospital',
       'carterpuri village', 'sector 58', 'new sector 2 phase 1',
       ', delhi ncr', 'golf course ext road', 'civil l',
       'g block dlf city phase 1', 'sector 15 part 2',
       'sector 4, railway road,', 'block h sector 3 phase iii extension',
       'sec 3 bhim vihar part 1 bhimgher kheri', 'patel nagar',
       'surat nagar', 'park view', 'sector 3 phase 3',
       'saraswati enclave', 'shanti nagar', 'sector 17c', 'rajiv chowk',
       'west sector 13', 'kheri', 'near khandsa road',
       'near pataudi chowk', 'sector-35 sohna road', 'vir nagar',
       'mayfield garden', 'part 3 sector 5', 'near euro',
       'sector 3 phase i', 'ambience island', 'hira nagar',
       'lajpat nagar', 'bhora kalan', 'b1 block sector 57',
       'anand garden, sector-105', 'begampur khatola',
       'hsiidc plot sector 1 manesar', 'sector 23a', 'kanahi',
       'cyber city', 'new sector 7', 'rajiv colony', 'bissar',
       'sector 3a', 'sector 9b', 'godrej aria , sector 79 ,',
       'saroop garden sector 105', 'hno 13 sagar enclave sura',
       'huda sector 28', 'alipur', 'near sector 1 market', 'sai kunj',
       'sispal vihar', 'old delhi road, opp sector-14',
       'urban estate, sector 5', 'sadar bazar', 'shivji park colony',
       'damdma', 'sector-2 sohna road', 'sector 7, sector 7', 'sector 42',
       'sector 4 urban estate', 'pataudi road', 'sector 5 chowk',
       'lucknow', 'jat colony,fazilpur/taj nagar road',
       'sector-5 sohna road', 'naharpur rupa', 'ram nagar',
       'mahasector 11, rajendra place',
       'devi lal colony gali no 12 gurgaon nr omkar public school',
       "ansal's sector 2", 'bptp', 'garauli kalan', 'sector 37a',
       'tekchand nagar', 'sector-7 hous'], dtype=object)

In [186]:
import re

# Dictionary for Villages, Colonies, and Roads
location_mapping = {
    'dhankot': 'sector 102',
    'shankar vihar': 'sector 104',
    'rattan garden': 'sector 7',
    'manohar nagar': 'sector 8',
    'new basti': 'sector 8',
    'gwal pahari': 'sector 58',
    'surat nagar phase 2': 'sector 104',
    'surat nagar': 'sector 104',
    'mohan nagar': 'sector 5',
    'heritage city': 'sector 25',
    'ats marigold': 'sector 89a',
    'acharya puri': 'sector 14',
    'om nagar': 'sector 11',
    'mahavir pura': 'sector 11',
    'udyog vihar phase 1': 'sector 20',
    'maruti kunj': 'sector 68',
    'south city': 'sector 41',
    'ravi nager basai road': 'sector 9',
    'daulatabad': 'sector 103',
    'laxmna vihar, phase 2': 'sector 3a',
    'samaspur': 'sector 51',
    'bhawani enclave': 'sector 9',
    'sushant lok': 'sector 43',
    'khandsa': 'sector 37',
    'sheetla colony': 'sector 5',
    'carterpuri village': 'sector 23a',
    'civil l': 'sector 15',
    'patel nagar': 'sector 15',
    'park view': 'sector 48',
    'saraswati enclave': 'sector 10b',
    'shanti nagar': 'sector 11',
    'rajiv chowk': 'sector 33',
    'kheri': 'sector 3',
    'vir nagar': 'sector 10a',
    'mayfield garden': 'sector 51',
    'ambience island': 'sector 24',
    'hira nagar': 'sector 11',
    'lajpat nagar': 'sector 6',
    'begampur khatola': 'sector 74',
    'kanahi': 'sector 45',
    'cyber city': 'sector 24',
    'rajiv colony': 'sector 33',
    'sai kunj': 'sector 110',
    'sispal vihar': 'sector 49',
    'sadar bazar': 'sector 12',
    'shivji park colony': 'sector 10a',
    'naharpur rupa': 'sector 33',
    'ram nagar': 'sector 8',
    'garauli kalan': 'sector 37d',
    'tekchand nagar': 'sector 10',
    'iffco chowk': 'sector 29',
    
    # Roads & Broad Areas (Mapped to representative sectors)
    'sohna road': 'sector 48',
    'sohna road road': 'sector 48',
    'sohna road  road': 'sector 48',
    'dwarka expressway': 'sector 109',
    'golf course road': 'sector 54',
    'golf course ext road': 'sector 62',
    'pataudi road': 'sector 10',
    'faridabad road': 'sector 2',
    
    # Typos & Specific buildings
    'ashok vihar phase 2': 'sector 5',
    'near nand hospital': 'sector 4',
    'near euro': 'sector 10', # Euro International usually in Sec 10
    'near khandsa road': 'sector 37',
    'near pataudi chowk': 'sector 10',
    'near sector 1 market': 'sector 1'
}

# 1. Apply the dictionary mapping
df['sector'] = df['sector'].replace(location_mapping)

In [187]:
# 2. Extract standard sector names from messy strings
# Yeh code automatically 'b block sector 43' ko 'sector 43' bana dega
def clean_sector_names(text):
    if pd.isna(text):
        return text
    
    # Check if 'sector' is in the text
    match = re.search(r'(sector\s*-?\s*\d+[a-zA-Z]?)', str(text), re.IGNORECASE)
    if match:
        # Standardize format: "sector 43", "sector 89a"
        cleaned = match.group(1).replace('-', ' ').replace('  ', ' ').lower()
        return cleaned
    return text

# Apply the regex cleaning function
df['sector'] = df['sector'].apply(clean_sector_names)

# Optional: Drop outside cities/junk data entirely
out_of_bounds = ['lucknow', 'farukhnagar', 'sultanpur', 'bhora kalan', 'gopal nagar, garhi ghasita, sonipat', ', delhi ncr', 'damdma', 'new']
df['sector'] = df['sector'].replace(out_of_bounds, pd.NA)

In [188]:
df['sector'].value_counts()

sector
sector 48                                                    234
sector 102                                                   114
sector 85                                                    110
sector 92                                                    104
sector 109                                                    96
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 79                                                     81
sector 104                                                    79
sector 33                                                     78
sector 2                                                      77
sector 37d                                                    69
sector 43                                                     69
sector 83                                                     69
sector 86                                                     67
sector 50                                                     66
sector 89                                                     64
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector 4                                                      52
sector 84                                                     51
sector 26                                                     50
sector 49                                                     50
sector 67                                                     48
sector 28                                                     48
sector 103                                                    47
sector 66                                                     46
sector 3                                                      44
sector 25                                                     44
sector 113                                                    43
sector 7                                                      43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 54                                                     33
sector 68                                                     33
sector 99a                                                    32
sector 12                                                     32
sector 11                                                     30
sector 72                                                     29
sector 77                                                     29
sector 24                                                     28
sector 71                                                     27
sector 57                                                     26
sector 14                                                     26
sector 58                                                     25
sector 105                                                    25
sector 112                                                    24
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 1                                                      22
sector 110                                                    20
sector 82a                                                    20
sector 22                                                     20
sector 62                                                     19
sector 78                                                     19
sector 74                                                     19
sector 47                                                     19
sector 63a                                                    18
sector 91                                                     17
sector 9                                                      16
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 6                                                      15
sector 5                                                      15
sector 55                                                     14
sector 52                                                     14
sector 76                                                     14
sector 53                                                     14
sector 8                                                      13
sector 46                                                     13
sector 36a                                                    13
sector 31                                                     12
sector 93                                                     12
sector 39                                                     12
sector 41                                                     12
sector 13                                                     12
sector 38                                                     12
sector 36                                                     11
sector 51                                                     11
sector 15                                                     11
sector 9a                                                     11
sector 45                                                     10
sector 1a                                                     10
sector 10a                                                    10
manesar                                                        9
sector 95a                                                     9
sector 59                                                      8
sector 21                                                      8
sector 40                                                      8
sector 17                                                      8
sector 23                                                      8
sector 23a                                                     6
sector 80                                                      5
sector 30                                                      5
sector 3a                                                      5
sector 10                                                      4
sector 12a                                                     4
sector 73                                                      3
sector 17b                                                     3
sector 17a                                                     3
sector 88b                                                     3
sector 27                                                      3
rosewood                                                       2
sector 29                                                      2
bissar                                                         2
pratap nagar                                                   2
sector 32                                                      2
sector 37                                                      2
nars                                                           2
sector 37b                                                     1
bhimgarh kheri phase 3                                         1
sector 20                                                      1
sector 21a                                                     1
sector 89a                                                     1
g block dlf city phase 1                                       1
sector 10b                                                     1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 17c                                                     1
sector 35                                                      1
sector 9b                                                      1
hno 13 sagar enclave sura                                      1
alipur                                                         1
sector 42                                                      1
jat colony,fazilpur/taj nagar road                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
bptp                                                           1
sector 37a                                                     1
Name: count, dtype: int64

In [189]:
# Is naye block ko apni purani dictionary mein merge kar lijiye
additional_mapping = {
    'manesar': 'sector 1 manesar',
    'rosewood': 'sector 49',             # Rosewood City Sector 49/50 mein aati hai
    'pratap nagar': 'sector 8',
    'bissar': pd.NA,                     # Bissar (Bissar Akbarpur) Tauru ke paas hai, Gurgaon city limits se baahar.
    'nars': 'sector 36a',                # 'nars' usually Narsinghpur ke liye use hota hai
    'bhimgarh kheri phase 3': 'sector 3',
    'g block dlf city phase 1': 'sector 26', # DLF Phase 1 pura Sector 26 hai
    'sec 3 bhim vihar part 1 bhimgher kheri': 'sector 3',
    'hno 13 sagar enclave sura': 'sector 104', # Surat Nagar area ke paas
    'alipur': 'sector 68',               # Alipur village Sohna Road/Sec 68 ke paas hai
    'jat colony,fazilpur/taj nagar road': 'sector 72', # Fazilpur area
    'devi lal colony gali no 12 gurgaon nr omkar public school': 'sector 9',
    'bptp': 'sector 37d'                 # Note: BPTP ke Sec 37D, 70A aur 102 mein projects hain, 37D sabse common hai
}

# Dictionary ko update karein aur apply karein
location_mapping.update(additional_mapping)
df['sector'] = df['sector'].replace(location_mapping)

In [190]:
df['sector'].value_counts()

sector
sector 48           234
sector 102          114
sector 85           110
sector 92           104
sector 109           96
sector 69            94
sector 90            90
sector 81            90
sector 65            90
sector 79            81
sector 104           80
sector 33            78
sector 2             77
sector 37d           70
sector 43            69
sector 83            69
sector 86            67
sector 50            66
sector 89            64
sector 107           60
sector 108           59
sector 95            57
sector 56            57
sector 70a           54
sector 70            53
sector 37c           53
sector 49            52
sector 4             52
sector 84            51
sector 26            51
sector 67            48
sector 28            48
sector 103           47
sector 3             46
sector 66            46
sector 25            44
sector 7             43
sector 113           43
sector 82            42
sector 61            42
sector 106           38
sector 68            34
sector 54            33
sector 12            32
sector 99a           32
sector 11            30
sector 72            30
sector 77            29
sector 24            28
sector 71            27
sector 14            26
sector 57            26
sector 58            25
sector 105           25
sector 112           24
sector 88a           23
sector 67a           22
sector 111           22
sector 1             22
sector 82a           20
sector 22            20
sector 110           20
sector 47            19
sector 74            19
sector 78            19
sector 62            19
sector 63a           18
sector 91            17
sector 9             17
sector 99            16
sector 60            15
sector 63            15
sector 6             15
sector 5             15
sector 36a           15
sector 8             15
sector 52            14
sector 76            14
sector 55            14
sector 53            14
sector 46            13
sector 38            12
sector 31            12
sector 93            12
sector 41            12
sector 13            12
sector 39            12
sector 36            11
sector 51            11
sector 9a            11
sector 15            11
sector 1a            10
sector 45            10
sector 10a           10
sector 95a            9
sector 1 manesar      9
sector 23             8
sector 40             8
sector 17             8
sector 59             8
sector 21             8
sector 23a            6
sector 30             5
sector 80             5
sector 3a             5
sector 12a            4
sector 10             4
sector 17a            3
sector 73             3
sector 27             3
sector 88b            3
sector 17b            3
sector 32             2
sector 29             2
sector 37             2
sector 37b            1
sector 89a            1
sector 21a            1
sector 20             1
sector 10b            1
sector 17c            1
sector 35             1
sector 9b             1
sector 42             1
sector 37a            1
Name: count, dtype: int64

In [191]:
df['sector']=df['sector'].str.split(" ").str.get(1)

In [192]:
df['sector'].value_counts()

sector
48     234
102    114
85     110
92     104
109     96
69      94
90      90
81      90
65      90
79      81
104     80
33      78
2       77
37d     70
83      69
43      69
86      67
50      66
89      64
107     60
108     59
56      57
95      57
70a     54
70      53
37c     53
4       52
49      52
84      51
26      51
67      48
28      48
103     47
3       46
66      46
25      44
113     43
7       43
61      42
82      42
106     38
68      34
54      33
99a     32
12      32
1       31
11      30
72      30
77      29
24      28
71      27
14      26
57      26
58      25
105     25
112     24
88a     23
67a     22
111     22
22      20
82a     20
110     20
78      19
74      19
47      19
62      19
63a     18
9       17
91      17
99      16
63      15
8       15
5       15
60      15
36a     15
6       15
76      14
55      14
52      14
53      14
46      13
38      12
93      12
41      12
13      12
31      12
39      12
9a      11
51      11
36      11
15      11
1a      10
10a     10
45      10
95a      9
23       8
40       8
17       8
59       8
21       8
23a      6
30       5
80       5
3a       5
10       4
12a      4
73       3
17b      3
17a      3
88b      3
27       3
32       2
29       2
37       2
37b      1
89a      1
21a      1
20       1
10b      1
17c      1
35       1
9b       1
42       1
37a      1
Name: count, dtype: int64

In [193]:
df['sector'] = df['sector'].str.extract(r'(\d+)').astype(float)

In [194]:
df[df['sector'].isnull()]

,property_name,property_type,society,sector,price_in_crore,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
449,6 Bedroom House for sale in Farukhnagar,house,independent,NaN,2.30,25386.0,906.0,Plot area 906(84.17 sq.m.),6,6,0,others,"Ward No 9, Farukhnagar, Gurgaon, Haryana",0.0,NaN,10+ Year Old,"['Dr. Manish Pandey', 'Shri Bala G Hospital an...",Property with an open area with 6 room and 6 b...,NaN,"['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
511,3 Bedroom House for sale in Farukhnagar,house,independent,NaN,0.52,5778.0,900.0,Plot area 100(83.61 sq.m.),3,2,2,not available,"Farukhnagar, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Dr. Manish Pandey', 'Verma Dental Clinic', '...",Interested to sell independent house/villa.Pla...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
517,4 BHK Flat in New Gurgaon,flat,dlf 76,NaN,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
590,"4 Bedroom House for sale in Gopal Nagar, Garhi...",house,independent,NaN,1.00,11111.0,900.0,Plot area 100(83.61 sq.m.),4,3,3+,others,"162/28, Gopal Nagar, Garhi Ghasita, Near Malik...",4.0,North-East,1 to 5 Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","A. New building, \nB. Basement+duplex showroom...","['1 Water Purifier', '1 Exhaust Fan', '1 Chimn...",NaN,NaN
616,3 BHK Flat in Sultanpur,flat,empire estate,NaN,3.50,16666.0,2100.0,Super Built up area 2100(195.1 sq.m.),3,3,2,servant room,"Sultanpur, Gurgaon, Haryana",3.0,North-West,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",Empire estate is one of the most popular desti...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '1 Mo...","['Water purifier', 'Security / Fire Alarm', 'F...",NaN
1123,4 BHK Flat in New Gurgaon,flat,sare homes,NaN,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1318,2 BHK Flat in New Gurgaon,flat,green court,NaN,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1488,"9 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,NaN,1.50,16667.0,900.0,Carpet area: 900 (83.61 sq.m.),9,3,3+,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",3.0,NaN,undefined,NaN,9bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2332,2 Bedroom House for sale in Bhora Kalan,house,independent,NaN,0.15,2296.0,653.0,Plot area 75(62.71 sq.m.),2,1,0,not available,"Bhora Kalan, Gurgaon, Haryana",1.0,NaN,10+ Year Old,NaN,Interested to sell independent house/villa.Pla...,NaN,NaN,NaN
2725,3 Bedroom House for sale in Bissar,house,silverglades tarudhan valley golf resort,NaN,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others","Bissar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3072,2 Bedroom House for sale in Damdma,house,independent,NaN,0.18,4000.0,450.0,Plot area 450(41.81 sq.m.),2,1,1,not available,"Damdma, Gurgaon, Haryana",1.0,East,1 to 5 Year Old,NaN,"This is a 2 bhk house with plot for sale, its ...",NaN,NaN,NaN
3074,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,NaN,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3277,"5 Bedroom House for sale in Gurgaon, Delhi NCR",house,independent,NaN,0.50,3704.0,1350.0,Built Up area: 1350 (125.42 sq.m.),5,2,0,not available,"Gurgaon, Delhi NCR, Gurgaon, Haryana",2.0,NaN,undefined,NaN,5bhk residential house for resale in at gurgao...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
3520,3 Bedroom House for sale in Bissar,house,silverglades tarudhan valley golf resort,NaN,3.05,12551.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others","Bissar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,Wishing to settle down in an individual house ...,"['1 Water Purifier', '9 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3532,7 Bedroom House for sale in Lucknow,house,dlf garden city floors,NaN,4.00,17817.0,2245.0,Plot area 2245(208.57 sq.m.),7,7,3+,not available,"Lucknow, Gurgaon, Haryana",4.0,NaN,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",I have a house/villa available for sale in dlf...,[],"['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN

In [195]:
import pandas as pd
import numpy as np

# 1. Society ke naam se exact sector map karna (Hidden sectors & Errors)
society_sector_map = {
    'dlf 76': '76',
    'sare homes': '92',
    'green court': '90',
    'takshila heights sector 37 c': '37',
    'dlf garden city floors': '92' # Yeh 'Lucknow' wale error ko theek kar dega
}

# Jinke sector NaN hain, unka sector unki society ke basis pe fill karein
df['sector'] = df.apply(
    lambda row: society_sector_map.get(str(row['society']).strip().lower(), row['sector']) 
    if pd.isna(row['sector']) else row['sector'], 
    axis=1
)

In [196]:
df=df[~df['sector'].isnull()]

In [197]:
df['sector']=df['sector'].astype(int)

In [198]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [199]:
df.sample(5)

,property_type,society,sector,price_in_crore,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2181,house,ansal sushant residency,57,4.60,17037.0,2700.0,Plot area 300(250.84 sq.m.),6,6,3,"pooja room,study room,servant room,store room",3.0,East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
2356,house,independent,104,0.71,10142.0,700.0,Plot area 700(65.03 sq.m.),4,2,1,not available,2.0,NaN,0 to 1 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Dr. ...",NaN,NaN
3848,flat,dlf regal gardens,90,2.05,9000.0,2278.0,Super Built up area 2215(205.78 sq.m.),4,4,3+,not available,5.0,NaN,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F..."
82,flat,spaze privy at,84,1.35,9642.0,1400.0,Super Built up area 1918(178.19 sq.m.)Built Up...,3,3,3,pooja room,7.0,South-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Del...",NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ..."
266,flat,dnha cghs,1,0.85,3864.0,2200.0,Built Up area: 2200 (204.39 sq.m.),3,3,0,not available,5.0,NaN,undefined,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",NaN,NaN

In [200]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [201]:
df.duplicated().sum()

np.int64(125)

In [202]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)